resolver: lts-8.20

packages:
- '.'
- location:
    git: https://github.com/rybern/prob-seq.git
    commit: 11cfdfcb8d5d713d91c83620a8e4dfb0961a59b7
  extra-dep: true
#- '../prob-seq'
- location:
    git: https://github.com/rybern/construction-files.git
    commit: HEAD
  extra-dep: true

extra-deps: [ sparse-lin-alg-0.4.3
            , prob-seq-0.1.0.0
            , vector-0.12.0.0 ]

flags: {}

extra-package-dbs: []

nix:
  enable: true
  packages: [gcc, ncurses, git]
